# Generated by Django 4.1.7 on 2023-10-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="tg_user_id",
            field=models.CharField(
                blank=True,
                help_text="Ваш уникальный идентификационный номер пользователя телеграмма.Он необходим для отправки вам сообщений через телеграмм бот.Свой ID можно узнать здесь https://t.me/getmyid_bot",
                max_length=50,
                verbose_name="Ваш пользовательский ID в телеграмме",
            ),
        ),
    ]
